use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::{Path, PathBuf},
};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DllValueType {
    Float,
    Double,
    Int32,
    Int64,
    Bytes,
}

impl DllValueType {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Float => "Float (f32)",
            Self::Double => "Double (f64)",
            Self::Int32 => "Int32 (i32)",
            Self::Int64 => "Int64 (i64)",
            Self::Bytes => "Bytes (Hex NOP)",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DllPatchMode {
    Freeze,
    WriteOnce,
    NopInstruction,
    HotkeyToggle,
}

impl DllPatchMode {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Freeze => "Khóa liên tục (Freeze)",
            Self::WriteOnce => "Ghi 1 lần khi tiêm (Write Once)",
            Self::NopInstruction => "Vô hiệu hóa lệnh (NOP Instruction)",
            Self::HotkeyToggle => "Bật/Tắt bằng Phím tắt (Hotkey Toggle)",
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DllMemoryEntry {
    pub enabled: bool,
    pub name: String,
    pub address: String, // Hex string "0x1428ABC10" or "game.exe+0x1234"
    pub offsets: Vec<isize>,
    pub value_type: DllValueType,
    pub value_to_write: String,
    pub mode: DllPatchMode,
    pub hotkey_vk: Option<u32>, // Virtual Key e.g. VK_F1 = 0x70
}

impl Default for DllMemoryEntry {
    fn default() -> Self {
        Self {
            enabled: true,
            name: "Camera Pitch Lock".to_string(),
            address: "0x140000000".to_string(),
            offsets: vec![],
            value_type: DllValueType::Float,
            value_to_write: "89.0".to_string(),
            mode: DllPatchMode::HotkeyToggle,
            hotkey_vk: Some(0x70), // VK_F1
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DllProjectConfig {
    pub project_name: String,
    pub target_process: String,
    pub auto_uninject_on_exit: bool,
    pub alloc_console_for_debug: bool,
    pub entries: Vec<DllMemoryEntry>,
}

impl Default for DllProjectConfig {
    fn default() -> Self {
        Self {
            project_name: "MacroNest_CustomDLL".to_string(),
            target_process: "game.exe".to_string(),
            auto_uninject_on_exit: true,
            alloc_console_for_debug: true,
            entries: vec![DllMemoryEntry::default()],
        }
    }
}

/// Generates a standalone, self-contained C++ source code file (dllmain.cpp)
pub fn generate_c_source(config: &DllProjectConfig) -> String {
    use std::fmt::Write;
    let mut source = String::new();
    source.push_str("// Auto-generated by MacroNest Auto DLL Generator\n");
    source.push_str("#include <windows.h>\n");
    source.push_str("#include <iostream>\n");
    source.push_str("#include <vector>\n");
    source.push_str("#include <string>\n\n");

    source.push_str("// Helper: Resolve pointer chain inside target process memory space\n");
    source.push_str(
        "uintptr_t ResolvePointer(uintptr_t base_addr, const std::vector<ptrdiff_t>& offsets) {\n",
    );
    source.push_str("    uintptr_t addr = base_addr;\n");
    source.push_str("    for (size_t i = 0; i < offsets.size(); ++i) {\n");
    source
        .push_str("        if (!addr || IsBadReadPtr((void*)addr, sizeof(uintptr_t))) return 0;\n");
    source.push_str("        addr = *(uintptr_t*)addr + offsets[i];\n");
    source.push_str("    }\n");
    source.push_str("    return addr;\n");
    source.push_str("}\n\n");

    source.push_str("// Helper: Patch memory bytes (e.g. NOP instruction)\n");
    source.push_str(
        "bool PatchMemory(uintptr_t address, const std::vector<unsigned char>& bytes) {\n",
    );
    source.push_str("    DWORD old_protect;\n");
    source.push_str("    if (!VirtualProtect((void*)address, bytes.size(), PAGE_EXECUTE_READWRITE, &old_protect)) return false;\n");
    source.push_str("    memcpy((void*)address, bytes.data(), bytes.size());\n");
    source
        .push_str("    VirtualProtect((void*)address, bytes.size(), old_protect, &old_protect);\n");
    source.push_str("    return true;\n");
    source.push_str("}\n\n");

    source.push_str("DWORD WINAPI MainThread(LPVOID lpParam) {\n");
    if config.alloc_console_for_debug {
        source.push_str("    AllocConsole();\n");
        source.push_str("    FILE* f; freopen_s(&f, \"CONOUT$\", \"w\", stdout);\n");
        source.push_str(
            "    std::cout << \"[MacroNest DLL] Injected successfully into target process!\\n\";\n",
        );
    }

    // Output entry states
    for (idx, entry) in config.entries.iter().enumerate() {
        if !entry.enabled {
            continue;
        }
        let _ = writeln!(source, "    bool state_entry_{idx} = false;");
        let _ = writeln!(source, "    bool last_key_{idx} = false;");
    }

    source.push_str("\n    while (true) {\n");

    for (idx, entry) in config.entries.iter().enumerate() {
        if !entry.enabled {
            continue;
        }
        let vk_code = entry.hotkey_vk.unwrap_or(0x70 + idx as u32);
        let _ = writeln!(source, "        // Entry {idx}: {}", entry.name);

        // Hotkey check
        let _ = writeln!(
            source,
            "        bool key_down_{idx} = (GetAsyncKeyState(0x{vk_code:X}) & 0x8000) != 0;"
        );
        let _ = writeln!(
            source,
            "        if (key_down_{idx} && !last_key_{idx}) {{"
        );
        let _ = writeln!(
            source,
            "            state_entry_{idx} = !state_entry_{idx};"
        );
        if config.alloc_console_for_debug {
            let _ = writeln!(
                source,
                "            std::cout << \"[MacroNest DLL] Toggled {}: \" << (state_entry_{idx} ? \"ON\" : \"OFF\") << \"\\n\";",
                entry.name
            );
        }
        let _ = writeln!(
            source,
            "        }}\n        last_key_{idx} = key_down_{idx};\n"
        );

        // Action implementation
        if entry.mode == DllPatchMode::HotkeyToggle {
            let _ = writeln!(source, "        if (state_entry_{idx}) {{");
        } else {
            let _ = writeln!(source, "        if (true) {{");
        }

        // Parse address
        if entry.address.starts_with("0x") || entry.address.starts_with("0X") {
            let _ = writeln!(source, "            uintptr_t target_addr = {};", entry.address);
        } else {
            let _ = writeln!(source, "            uintptr_t target_addr = 0x{};", entry.address);
        }

        if !entry.offsets.is_empty() {
            let _ = write!(source, "            target_addr = ResolvePointer(target_addr, {{");
            for (oi, o) in entry.offsets.iter().enumerate() {
                if oi > 0 {
                    let _ = write!(source, ", ");
                }
                if *o < 0 {
                    let _ = write!(source, "-0x{:X}", -*o);
                } else {
                    let _ = write!(source, "0x{o:X}");
                }
            }
            let _ = writeln!(source, "}});");
        }

        source.push_str("            if (target_addr) {\n");
        match entry.value_type {
            DllValueType::Float => {
                let val: f32 = entry.value_to_write.parse().unwrap_or(0.0);
                let _ = writeln!(source, "                *(float*)target_addr = {val}f;");
            }
            DllValueType::Double => {
                let val: f64 = entry.value_to_write.parse().unwrap_or(0.0);
                let _ = writeln!(source, "                *(double*)target_addr = {val};");
            }
            DllValueType::Int32 => {
                let val: i32 = entry.value_to_write.parse().unwrap_or(0);
                let _ = writeln!(source, "                *(int32_t*)target_addr = {val};");
            }
            DllValueType::Int64 => {
                let val: i64 = entry.value_to_write.parse().unwrap_or(0);
                let _ = writeln!(source, "                *(int64_t*)target_addr = {val}LL;");
            }
            DllValueType::Bytes => {
                let byte_vals: Vec<u8> = entry
                    .value_to_write
                    .split_whitespace()
                    .filter_map(|s| u8::from_str_radix(s, 16).ok())
                    .collect();
                if !byte_vals.is_empty() {
                    let _ = write!(source, "                PatchMemory(target_addr, {{");
                    for (bi, b) in byte_vals.iter().enumerate() {
                        if bi > 0 {
                            let _ = write!(source, ", ");
                        }
                        let _ = write!(source, "0x{b:02X}");
                    }
                    let _ = writeln!(source, "}});");
                }
            }
        }
        source.push_str("            }\n");
        source.push_str("        }\n\n");
    }

    source.push_str("        Sleep(5);\n");
    source.push_str("    }\n");
    source.push_str("    return 0;\n");
    source.push_str("}\n\n");

    source.push_str(
        "BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved) {\n",
    );
    source.push_str("    if (ul_reason_for_call == DLL_PROCESS_ATTACH) {\n");
    source.push_str("        DisableThreadLibraryCalls(hModule);\n");
    source.push_str("        CreateThread(NULL, 0, MainThread, NULL, 0, NULL);\n");
    source.push_str("    }\n");
    source.push_str("    return TRUE;\n");
    source.push_str("}\n");

    source
}

/// Generates a Frida JavaScript script representing the DLL patch configuration
pub fn generate_frida_js_script(config: &DllProjectConfig) -> String {
    use std::fmt::Write;
    let mut script = String::new();
    script.push_str("// Auto-generated by MacroNest DLL Studio (Frida Hook Script)\n");
    script.push_str("console.log('[MacroNest Frida Script] Loaded successfully!');\n\n");

    for (idx, entry) in config.entries.iter().enumerate() {
        if !entry.enabled {
            continue;
        }
        let _ = writeln!(script, "// Entry {idx}: {}", entry.name);
        script.push_str("try {\n");
        let _ = writeln!(script, "    const targetAddr_{idx} = ptr('{}');", entry.address);
        match entry.value_type {
            DllValueType::Float => {
                let val: f32 = entry.value_to_write.parse().unwrap_or(0.0);
                let _ = writeln!(script, "    Memory.writeFloat(targetAddr_{idx}, {val});");
            }
            DllValueType::Double => {
                let val: f64 = entry.value_to_write.parse().unwrap_or(0.0);
                let _ = writeln!(script, "    Memory.writeDouble(targetAddr_{idx}, {val});");
            }
            DllValueType::Int32 => {
                let val: i32 = entry.value_to_write.parse().unwrap_or(0);
                let _ = writeln!(script, "    Memory.writeInt(targetAddr_{idx}, {val});");
            }
            DllValueType::Int64 => {
                let val: i64 = entry.value_to_write.parse().unwrap_or(0);
                let _ = writeln!(script, "    Memory.writeS64(targetAddr_{idx}, int64('{val}'));");
            }
            DllValueType::Bytes => {
                let byte_vals: Vec<u8> = entry
                    .value_to_write
                    .split_whitespace()
                    .filter_map(|s| u8::from_str_radix(s, 16).ok())
                    .collect();
                if !byte_vals.is_empty() {
                    let _ = writeln!(
                        script,
                        "    Memory.protect(targetAddr_{idx}, {}, 'rwx');",
                        byte_vals.len()
                    );
                    let _ = write!(script, "    targetAddr_{idx}.writeByteArray([");
                    for (bi, b) in byte_vals.iter().enumerate() {
                        if bi > 0 {
                            let _ = write!(script, ", ");
                        }
                        let _ = write!(script, "0x{b:02x}");
                    }
                    let _ = writeln!(script, "]);");
                }
            }
        }
        let _ = writeln!(
            script,
            "    console.log('[MacroNest Frida Script] Applied patch for {}');",
            entry.name
        );
        script.push_str("} catch (err) {\n");
        let _ = writeln!(
            script,
            "    console.error('[MacroNest Frida Script] Error patching {}: ' + err.message);",
            entry.name
        );
        script.push_str("}\n\n");
    }

    script
}

/// Exports complete project folder containing C++ code, build script, and Frida JS
pub fn export_dll_project(config: &DllProjectConfig, export_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(export_dir)?;

    let cpp_source = generate_c_source(config);
    let js_script = generate_frida_js_script(config);

    let cpp_path = export_dir.join("dllmain.cpp");
    let js_path = export_dir.join("script.js");
    let bat_path = export_dir.join("build_vs.bat");
    let readme_path = export_dir.join("README.txt");

    fs::write(&cpp_path, cpp_source)?;
    fs::write(&js_path, js_script)?;

    let bat_content = format!(
        "@echo off\n\
        echo Building DLL: {}\n\
        call \"%%VS2022INSTALLDIR%%\\VC\\Auxiliary\\Build\\vcvars64.bat\"\n\
        cl /LD /EHsc /O2 dllmain.cpp /Fe:{}.dll /link /DLL\n\
        echo Build finished!\n\
        pause\n",
        config.project_name, config.project_name
    );
    fs::write(&bat_path, bat_content)?;

    let readme_content = format!(
        "MacroNest Auto DLL Generator Project: {}\n\
        Target Application: {}\n\n\
        Files in this folder:\n\
        1. dllmain.cpp - Standalone C++ source code for your DLL.\n\
        2. script.js - Frida JavaScript memory patch script.\n\
        3. build_vs.bat - Double click to build using Visual Studio C++ Compiler.\n\n\
        How to use:\n\
        - Open Visual Studio and build dllmain.cpp into a .dll file.\n\
        - Or use MacroNest Direct Injector to inject script/DLL into target process.\n",
        config.project_name, config.target_process
    );
    fs::write(&readme_path, readme_content)?;

    Ok(export_dir.to_path_buf())
}

/// Injects a specified DLL file path into a running process PID using Windows API
#[cfg(windows)]
pub fn inject_dll_into_process(pid: u32, dll_path: &Path) -> Result<()> {
    use windows_sys::Win32::{
        Foundation::{CloseHandle, HANDLE},
        System::{
            Diagnostics::Debug::WriteProcessMemory,
            LibraryLoader::{GetModuleHandleA, GetProcAddress},
            Memory::{MEM_COMMIT, MEM_RESERVE, PAGE_READWRITE, VirtualAllocEx},
            Threading::{
                CreateRemoteThread, OpenProcess, PROCESS_CREATE_THREAD, PROCESS_QUERY_INFORMATION,
                PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE,
            },
        },
    };

    let canonical_path = fs::canonicalize(dll_path).unwrap_or_else(|_| dll_path.to_path_buf());
    let path_str = canonical_path.to_str().context("Invalid DLL path string")?;

    let wide_path: Vec<u16> = path_str.encode_utf16().chain(std::iter::once(0)).collect();
    let path_bytes_len = wide_path.len() * 2;

    unsafe {
        let process_handle: HANDLE = OpenProcess(
            PROCESS_CREATE_THREAD
                | PROCESS_QUERY_INFORMATION
                | PROCESS_VM_OPERATION
                | PROCESS_VM_WRITE
                | PROCESS_VM_READ,
            0,
            pid,
        );

        if process_handle.is_null() {
            bail!(
                "Failed to open process PID {} (Access Denied or Invalid PID)",
                pid
            );
        }

        let alloc_addr = VirtualAllocEx(
            process_handle,
            std::ptr::null_mut(),
            path_bytes_len,
            MEM_COMMIT | MEM_RESERVE,
            PAGE_READWRITE,
        );

        if alloc_addr.is_null() {
            CloseHandle(process_handle);
            bail!("Failed to allocate memory inside process PID {}", pid);
        }

        let mut bytes_written: usize = 0;
        let write_res = WriteProcessMemory(
            process_handle,
            alloc_addr,
            wide_path.as_ptr() as *const _,
            path_bytes_len,
            &mut bytes_written,
        );

        if write_res == 0 {
            CloseHandle(process_handle);
            bail!("Failed to write DLL path into target process memory");
        }

        let kernel32_name = std::ffi::CString::new("kernel32.dll").unwrap();
        let load_library_name = std::ffi::CString::new("LoadLibraryW").unwrap();

        let kernel32_mod = GetModuleHandleA(kernel32_name.as_ptr() as *const u8);
        if kernel32_mod.is_null() {
            CloseHandle(process_handle);
            bail!("Failed to get kernel32.dll module handle");
        }

        let load_library_addr =
            GetProcAddress(kernel32_mod, load_library_name.as_ptr() as *const u8);
        if load_library_addr.is_none() {
            CloseHandle(process_handle);
            bail!("Failed to get LoadLibraryW address");
        }

        let thread_handle = CreateRemoteThread(
            process_handle,
            std::ptr::null(),
            0,
            std::mem::transmute(load_library_addr),
            alloc_addr,
            0,
            std::ptr::null_mut(),
        );

        if thread_handle.is_null() {
            CloseHandle(process_handle);
            bail!("Failed to create remote thread in process PID {}", pid);
        }

        CloseHandle(thread_handle);
        CloseHandle(process_handle);
    }

    Ok(())
}

#[cfg(not(windows))]
pub fn inject_dll_into_process(_pid: u32, _dll_path: &Path) -> Result<()> {
    bail!("DLL injection is only supported on Windows OS");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_c_source_and_frida_script_produces_expected_output() {
        let config = DllProjectConfig {
            project_name: "TestDLL".to_owned(),
            target_process: "target.exe".to_owned(),
            auto_uninject_on_exit: true,
            alloc_console_for_debug: false,
            entries: vec![
                DllMemoryEntry {
                    enabled: true,
                    name: "Freeze Entry".to_owned(),
                    address: "0x140001000".to_owned(),
                    offsets: vec![0x10, 0x20],
                    value_type: DllValueType::Float,
                    value_to_write: "100.0".to_owned(),
                    mode: DllPatchMode::Freeze,
                    hotkey_vk: Some(0x70),
                },
                DllMemoryEntry {
                    enabled: true,
                    name: "Hotkey Entry".to_owned(),
                    address: "140002000".to_owned(),
                    offsets: vec![],
                    value_type: DllValueType::Bytes,
                    value_to_write: "90 90 CC".to_owned(),
                    mode: DllPatchMode::HotkeyToggle,
                    hotkey_vk: Some(0x71),
                },
            ],
        };

        let c_source = generate_c_source(&config);
        assert!(c_source.contains("ResolvePointer(target_addr, {0x10, 0x20})"));
        assert!(c_source.contains("if (true) {"));
        assert!(c_source.contains("if (state_entry_1) {"));
        assert!(c_source.contains("PatchMemory(target_addr, {0x90, 0x90, 0xCC})"));
        assert!(!c_source.contains("mode_always"));

        let js_script = generate_frida_js_script(&config);
        assert!(js_script.contains("Memory.writeFloat(targetAddr_0, 100);"));
        assert!(js_script.contains("targetAddr_1.writeByteArray([0x90, 0x90, 0xcc]);"));
    }
}

