use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::{Path, PathBuf},
};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DllValueType {
    Float,
    Double,
    Int32,
    Int64,
    Bytes,
}

impl DllValueType {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Float => "Float (f32)",
            Self::Double => "Double (f64)",
            Self::Int32 => "Int32 (i32)",
            Self::Int64 => "Int64 (i64)",
            Self::Bytes => "Bytes (Hex NOP)",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DllPatchMode {
    Freeze,
    WriteOnce,
    NopInstruction,
    HotkeyToggle,
}

impl DllPatchMode {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Freeze => "Khóa liên tục (Freeze)",
            Self::WriteOnce => "Ghi 1 lần khi tiêm (Write Once)",
            Self::NopInstruction => "Vô hiệu hóa lệnh (NOP Instruction)",
            Self::HotkeyToggle => "Bật/Tắt bằng Phím tắt (Hotkey Toggle)",
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DllMemoryEntry {
    pub enabled: bool,
    pub name: String,
    pub address: String, // Hex string "0x1428ABC10" or "game.exe+0x1234"
    pub offsets: Vec<usize>,
    pub value_type: DllValueType,
    pub value_to_write: String,
    pub mode: DllPatchMode,
    pub hotkey_vk: Option<u32>, // Virtual Key e.g. VK_F1 = 0x70
}

impl Default for DllMemoryEntry {
    fn default() -> Self {
        Self {
            enabled: true,
            name: "Camera Pitch Lock".to_string(),
            address: "0x140000000".to_string(),
            offsets: vec![],
            value_type: DllValueType::Float,
            value_to_write: "89.0".to_string(),
            mode: DllPatchMode::HotkeyToggle,
            hotkey_vk: Some(0x70), // VK_F1
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DllProjectConfig {
    pub project_name: String,
    pub target_process: String,
    pub auto_uninject_on_exit: bool,
    pub alloc_console_for_debug: bool,
    pub entries: Vec<DllMemoryEntry>,
}

impl Default for DllProjectConfig {
    fn default() -> Self {
        Self {
            project_name: "MacroNest_CustomDLL".to_string(),
            target_process: "game.exe".to_string(),
            auto_uninject_on_exit: true,
            alloc_console_for_debug: true,
            entries: vec![DllMemoryEntry::default()],
        }
    }
}

/// Generates a standalone, self-contained C++ source code file (dllmain.cpp)
pub fn generate_c_source(config: &DllProjectConfig) -> String {
    let mut source = String::new();
    source.push_str("// Auto-generated by MacroNest Auto DLL Generator\n");
    source.push_str("#include <windows.h>\n");
    source.push_str("#include <iostream>\n");
    source.push_str("#include <vector>\n");
    source.push_str("#include <string>\n\n");

    source.push_str("// Helper: Resolve pointer chain inside target process memory space\n");
    source.push_str("uintptr_t ResolvePointer(uintptr_t base_addr, const std::vector<size_t>& offsets) {\n");
    source.push_str("    uintptr_t addr = base_addr;\n");
    source.push_str("    for (size_t i = 0; i < offsets.size(); ++i) {\n");
    source.push_str("        if (!addr || IsBadReadPtr((void*)addr, sizeof(uintptr_t))) return 0;\n");
    source.push_str("        addr = *(uintptr_t*)addr + offsets[i];\n");
    source.push_str("    }\n");
    source.push_str("    return addr;\n");
    source.push_str("}\n\n");

    source.push_str("// Helper: Patch memory bytes (e.g. NOP instruction)\n");
    source.push_str("bool PatchMemory(uintptr_t address, const std::vector<unsigned char>& bytes) {\n");
    source.push_str("    DWORD old_protect;\n");
    source.push_str("    if (!VirtualProtect((void*)address, bytes.size(), PAGE_EXECUTE_READWRITE, &old_protect)) return false;\n");
    source.push_str("    memcpy((void*)address, bytes.data(), bytes.size());\n");
    source.push_str("    VirtualProtect((void*)address, bytes.size(), old_protect, &old_protect);\n");
    source.push_str("    return true;\n");
    source.push_str("}\n\n");

    source.push_str("DWORD WINAPI MainThread(LPVOID lpParam) {\n");
    if config.alloc_console_for_debug {
        source.push_str("    AllocConsole();\n");
        source.push_str("    FILE* f; freopen_s(&f, \"CONOUT$\", \"w\", stdout);\n");
        source.push_str("    std::cout << \"[MacroNest DLL] Injected successfully into target process!\\n\";\n");
    }

    // Output entry states
    for (idx, entry) in config.entries.iter().enumerate() {
        if !entry.enabled {
            continue;
        }
        source.push_str(&format!(
            "    bool state_entry_{} = false;\n",
            idx
        ));
        source.push_str(&format!(
            "    bool last_key_{} = false;\n",
            idx
        ));
    }

    source.push_str("\n    while (true) {\n");

    for (idx, entry) in config.entries.iter().enumerate() {
        if !entry.enabled {
            continue;
        }
        let vk_code = entry.hotkey_vk.unwrap_or(0x70 + idx as u32);
        source.push_str(&format!(
            "        // Entry {}: {}\n",
            idx, entry.name
        ));

        // Hotkey check
        source.push_str(&format!(
            "        bool key_down_{} = (GetAsyncKeyState(0x{:X}) & 0x8000) != 0;\n",
            idx, vk_code
        ));
        source.push_str(&format!(
            "        if (key_down_{} && !last_key_{}) {{\n",
            idx, idx
        ));
        source.push_str(&format!(
            "            state_entry_{} = !state_entry_{};\n",
            idx, idx
        ));
        if config.alloc_console_for_debug {
            source.push_str(&format!(
                "            std::cout << \"[MacroNest DLL] Toggled {}: \" << (state_entry_{} ? \"ON\" : \"OFF\") << \"\\n\";\n",
                entry.name, idx
            ));
        }
        source.push_str(&format!(
            "        }}\n        last_key_{} = key_down_{};\n\n",
            idx, idx
        ));

        // Action implementation
        source.push_str(&format!(
            "        if (state_entry_{} || mode_always_{}) {{\n",
            idx, idx
        ));

        // Parse address
        let addr_parsed = if entry.address.starts_with("0x") || entry.address.starts_with("0X") {
            entry.address.clone()
        } else {
            format!("0x{}", entry.address)
        };

        source.push_str(&format!(
            "            uintptr_t target_addr = {};\n",
            addr_parsed
        ));

        if !entry.offsets.is_empty() {
            let offsets_str = entry
                .offsets
                .iter()
                .map(|o| format!("0x{:X}", o))
                .collect::<Vec<_>>()
                .join(", ");
            source.push_str(&format!(
                "            target_addr = ResolvePointer(target_addr, {{{}}});\n",
                offsets_str
            ));
        }

        source.push_str("            if (target_addr) {\n");
        match entry.value_type {
            DllValueType::Float => {
                let val: f32 = entry.value_to_write.parse().unwrap_or(0.0);
                source.push_str(&format!(
                    "                *(float*)target_addr = {}f;\n",
                    val
                ));
            }
            DllValueType::Double => {
                let val: f64 = entry.value_to_write.parse().unwrap_or(0.0);
                source.push_str(&format!(
                    "                *(double*)target_addr = {};\n",
                    val
                ));
            }
            DllValueType::Int32 => {
                let val: i32 = entry.value_to_write.parse().unwrap_or(0);
                source.push_str(&format!(
                    "                *(int32_t*)target_addr = {};\n",
                    val
                ));
            }
            DllValueType::Int64 => {
                let val: i64 = entry.value_to_write.parse().unwrap_or(0);
                source.push_str(&format!(
                    "                *(int64_t*)target_addr = {}LL;\n",
                    val
                ));
            }
            DllValueType::Bytes => {
                let byte_vals: Vec<u8> = entry
                    .value_to_write
                    .split_whitespace()
                    .filter_map(|s| u8::from_str_radix(s, 16).ok())
                    .collect();
                if !byte_vals.is_empty() {
                    let bytes_cpp = byte_vals
                        .iter()
                        .map(|b| format!("0x{:02X}", b))
                        .collect::<Vec<_>>()
                        .join(", ");
                    source.push_str(&format!(
                        "                PatchMemory(target_addr, {{{}}});\n",
                        bytes_cpp
                    ));
                }
            }
        }
        source.push_str("            }\n");
        source.push_str("        }\n\n");
    }

    source.push_str("        Sleep(5);\n");
    source.push_str("    }\n");
    source.push_str("    return 0;\n");
    source.push_str("}\n\n");

    source.push_str("BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved) {\n");
    source.push_str("    if (ul_reason_for_call == DLL_PROCESS_ATTACH) {\n");
    source.push_str("        DisableThreadLibraryCalls(hModule);\n");
    source.push_str("        CreateThread(NULL, 0, MainThread, NULL, 0, NULL);\n");
    source.push_str("    }\n");
    source.push_str("    return TRUE;\n");
    source.push_str("}\n");

    // Replace dummy variable
    source = source.replace("|| mode_always_0", "|| true");
    source = source.replace("|| mode_always_1", "|| true");
    source = source.replace("|| mode_always_2", "|| true");
    source = source.replace("|| mode_always_3", "|| true");

    source
}

/// Generates a Frida JavaScript script representing the DLL patch configuration
pub fn generate_frida_js_script(config: &DllProjectConfig) -> String {
    let mut script = String::new();
    script.push_str("// Auto-generated by MacroNest DLL Studio (Frida Hook Script)\n");
    script.push_str("console.log('[MacroNest Frida Script] Loaded successfully!');\n\n");

    for (idx, entry) in config.entries.iter().enumerate() {
        if !entry.enabled {
            continue;
        }
        script.push_str(&format!(
            "// Entry {}: {}\n",
            idx, entry.name
        ));
        script.push_str(&format!(
            "try {{\n"
        ));
        script.push_str(&format!(
            "    const targetAddr_{} = ptr('{}');\n",
            idx, entry.address
        ));
        match entry.value_type {
            DllValueType::Float => {
                let val: f32 = entry.value_to_write.parse().unwrap_or(0.0);
                script.push_str(&format!(
                    "    Memory.writeFloat(targetAddr_{}, {});\n",
                    idx, val
                ));
            }
            DllValueType::Double => {
                let val: f64 = entry.value_to_write.parse().unwrap_or(0.0);
                script.push_str(&format!(
                    "    Memory.writeDouble(targetAddr_{}, {});\n",
                    idx, val
                ));
            }
            DllValueType::Int32 => {
                let val: i32 = entry.value_to_write.parse().unwrap_or(0);
                script.push_str(&format!(
                    "    Memory.writeInt(targetAddr_{}, {});\n",
                    idx, val
                ));
            }
            DllValueType::Int64 => {
                let val: i64 = entry.value_to_write.parse().unwrap_or(0);
                script.push_str(&format!(
                    "    Memory.writeS64(targetAddr_{}, int64('{}'));\n",
                    idx, val
                ));
            }
            DllValueType::Bytes => {
                let byte_vals: Vec<u8> = entry
                    .value_to_write
                    .split_whitespace()
                    .filter_map(|s| u8::from_str_radix(s, 16).ok())
                    .collect();
                if !byte_vals.is_empty() {
                    let hex_str = byte_vals
                        .iter()
                        .map(|b| format!("{:02x}", b))
                        .collect::<Vec<_>>()
                        .join("");
                    script.push_str(&format!(
                        "    Memory.protect(targetAddr_{}, {}, 'rwx');\n",
                        idx,
                        byte_vals.len()
                    ));
                    script.push_str(&format!(
                        "    targetAddr_{}.writeByteArray([{}]);\n",
                        idx,
                        byte_vals
                            .iter()
                            .map(|b| format!("0x{:02x}", b))
                            .collect::<Vec<_>>()
                            .join(", ")
                    ));
                }
            }
        }
        script.push_str(&format!(
            "    console.log('[MacroNest Frida Script] Applied patch for {}');\n",
            entry.name
        ));
        script.push_str("} catch (err) {\n");
        script.push_str(&format!(
            "    console.error('[MacroNest Frida Script] Error patching {}: ' + err.message);\n",
            entry.name
        ));
        script.push_str("}\n\n");
    }

    script
}

/// Exports complete project folder containing C++ code, build script, and Frida JS
pub fn export_dll_project(config: &DllProjectConfig, export_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(export_dir)?;

    let cpp_source = generate_c_source(config);
    let js_script = generate_frida_js_script(config);

    let cpp_path = export_dir.join("dllmain.cpp");
    let js_path = export_dir.join("script.js");
    let bat_path = export_dir.join("build_vs.bat");
    let readme_path = export_dir.join("README.txt");

    fs::write(&cpp_path, cpp_source)?;
    fs::write(&js_path, js_script)?;

    let bat_content = format!(
        "@echo off\n\
        echo Building DLL: {}\n\
        call \"%%VS2022INSTALLDIR%%\\VC\\Auxiliary\\Build\\vcvars64.bat\"\n\
        cl /LD /EHsc /O2 dllmain.cpp /Fe:{}.dll /link /DLL\n\
        echo Build finished!\n\
        pause\n",
        config.project_name, config.project_name
    );
    fs::write(&bat_path, bat_content)?;

    let readme_content = format!(
        "MacroNest Auto DLL Generator Project: {}\n\
        Target Application: {}\n\n\
        Files in this folder:\n\
        1. dllmain.cpp - Standalone C++ source code for your DLL.\n\
        2. script.js - Frida JavaScript memory patch script.\n\
        3. build_vs.bat - Double click to build using Visual Studio C++ Compiler.\n\n\
        How to use:\n\
        - Open Visual Studio and build dllmain.cpp into a .dll file.\n\
        - Or use MacroNest Direct Injector to inject script/DLL into target process.\n",
        config.project_name, config.target_process
    );
    fs::write(&readme_path, readme_content)?;

    Ok(export_dir.to_path_buf())
}

/// Injects a specified DLL file path into a running process PID using Windows API
#[cfg(windows)]
pub fn inject_dll_into_process(pid: u32, dll_path: &Path) -> Result<()> {
    use windows_sys::Win32::{
        Foundation::{CloseHandle, HANDLE},
        System::{
            Diagnostics::Debug::WriteProcessMemory,
            LibraryLoader::{GetProcAddress, GetModuleHandleA},
            Memory::{MEM_COMMIT, MEM_RESERVE, PAGE_READWRITE, VirtualAllocEx},
            Threading::{
                CreateRemoteThread, OpenProcess, PROCESS_CREATE_THREAD, PROCESS_QUERY_INFORMATION,
                PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE,
            },
        },
    };

    let canonical_path = fs::canonicalize(dll_path).unwrap_or_else(|_| dll_path.to_path_buf());
    let path_str = canonical_path.to_str().context("Invalid DLL path string")?;

    let wide_path: Vec<u16> = path_str.encode_utf16().chain(std::iter::once(0)).collect();
    let path_bytes_len = wide_path.len() * 2;

    unsafe {
        let process_handle: HANDLE = OpenProcess(
            PROCESS_CREATE_THREAD
                | PROCESS_QUERY_INFORMATION
                | PROCESS_VM_OPERATION
                | PROCESS_VM_WRITE
                | PROCESS_VM_READ,
            0,
            pid,
        );

        if process_handle.is_null() {
            bail!("Failed to open process PID {} (Access Denied or Invalid PID)", pid);
        }

        let alloc_addr = VirtualAllocEx(
            process_handle,
            std::ptr::null_mut(),
            path_bytes_len,
            MEM_COMMIT | MEM_RESERVE,
            PAGE_READWRITE,
        );

        if alloc_addr.is_null() {
            CloseHandle(process_handle);
            bail!("Failed to allocate memory inside process PID {}", pid);
        }

        let mut bytes_written: usize = 0;
        let write_res = WriteProcessMemory(
            process_handle,
            alloc_addr,
            wide_path.as_ptr() as *const _,
            path_bytes_len,
            &mut bytes_written,
        );

        if write_res == 0 {
            CloseHandle(process_handle);
            bail!("Failed to write DLL path into target process memory");
        }

        let kernel32_name = std::ffi::CString::new("kernel32.dll").unwrap();
        let load_library_name = std::ffi::CString::new("LoadLibraryW").unwrap();

        let kernel32_mod = GetModuleHandleA(kernel32_name.as_ptr() as *const u8);
        if kernel32_mod.is_null() {
            CloseHandle(process_handle);
            bail!("Failed to get kernel32.dll module handle");
        }

        let load_library_addr = GetProcAddress(kernel32_mod, load_library_name.as_ptr() as *const u8);
        if load_library_addr.is_none() {
            CloseHandle(process_handle);
            bail!("Failed to get LoadLibraryW address");
        }

        let thread_handle = CreateRemoteThread(
            process_handle,
            std::ptr::null(),
            0,
            std::mem::transmute(load_library_addr),
            alloc_addr,
            0,
            std::ptr::null_mut(),
        );

        if thread_handle.is_null() {
            CloseHandle(process_handle);
            bail!("Failed to create remote thread in process PID {}", pid);
        }

        CloseHandle(thread_handle);
        CloseHandle(process_handle);
    }

    Ok(())
}

#[cfg(not(windows))]
pub fn inject_dll_into_process(_pid: u32, _dll_path: &Path) -> Result<()> {
    bail!("DLL injection is only supported on Windows OS");
}
